### ISSUE TITLE
还是问题咨询。。。

### ISSUE THREAD

**Issue by kuri-leo** [XGowe/AutoFill4Attop#2]
您好！
我导入了那个配置后进去刷题，但并没有任何反应。。。
是我的打开方式不对吗？。。。

**Comment by kuri-leo** [comment]
问题已经解决，貌似和我的某些插件冲突了（怀疑是AdBlock
解决方法是开隐身模式进去刷，麻烦PO上去给大家说下吧

**Comment by XGowe** [comment]
经测试没有任何问题，请确认插件已启用，并尝试手动清理缓存并刷新页面。

**Comment by kuri-leo** [comment]
问题已经解决，是AdBlock引起的，禁用掉就可以正常使用了

同时，昨天使用时引起了至善网的崩溃：
就是一口气把所有页面打开完了，然后所有页面一起刷题。。。然后至善网整体崩溃
貌似至善网对这种短时间高并发访问的优化不怎么好，要不要考虑下在代码加入一个sleep降低访问的频率？

**Comment by XGowe** [comment]
你好，感谢反馈。
我不确定你说的整体崩溃是指什么。
这可能是本地网络带宽以及Chrome对单一网站套接字上限做了限制之缘故，导致部分窗口加载不完全，但在实际使用中经检测是可以正常工作的。
若确有需要可打开wk_online.js将15000替换为更长周期，并确认各窗口开启时间间隔数秒以降低同时并发，或考虑一次仅开启一半窗口。
后期计划实现单一窗口刷完后自动跳转至下一节以避免同时开启过多端口。

**Comment by kuri-leo** [comment]
应该是服务端的崩溃，当时是先网站无响应过了一会变成404，半个小时后恢复，校内其他同学当时也无法登录

**Comment by XGowe** [comment]
据可靠消息，近期至善网和超星慕课受到DDOS攻击。
这与此脚本无关，脚本产生的流量在可控范围内，无须担心。

2015-11-08 12:30 GMT+08:00 kuri-leo <notifications@github.com>:

> 应该是服务端的崩溃，当时是先网站无响应过了一会变成404，半个小时后恢复，校内其他同学当时也无法登录
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XGowe/AutoFill4Attop/issues/2#issuecomment-154775223>.
>



-- 
*Gowe*

**Comment by kuri-leo** [comment]
哦哦，谢谢
//果然都看不惯这几个网站啊。。。
